// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageLoginProto.proto

package com.nettyserver.pb;

public final class MessageLoginProto {
  private MessageLoginProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 aid = 1;
    boolean hasAid();
    int getAid();
    
    // optional string passport = 2;
    boolean hasPassport();
    String getPassport();
    
    // optional string password = 3;
    boolean hasPassword();
    String getPassword();
  }
  public static final class LoginRequest extends
      com.google.protobuf.GeneratedMessage
      implements LoginRequestOrBuilder {
    // Use LoginRequest.newBuilder() to construct.
    private LoginRequest(Builder builder) {
      super(builder);
    }
    private LoginRequest(boolean noInit) {}
    
    private static final LoginRequest defaultInstance;
    public static LoginRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nettyserver.pb.MessageLoginProto.internal_static_pb_message_LoginRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nettyserver.pb.MessageLoginProto.internal_static_pb_message_LoginRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 aid = 1;
    public static final int AID_FIELD_NUMBER = 1;
    private int aid_;
    public boolean hasAid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getAid() {
      return aid_;
    }
    
    // optional string passport = 2;
    public static final int PASSPORT_FIELD_NUMBER = 2;
    private java.lang.Object passport_;
    public boolean hasPassport() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPassport() {
      java.lang.Object ref = passport_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          passport_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPassportBytes() {
      java.lang.Object ref = passport_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        passport_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string password = 3;
    public static final int PASSWORD_FIELD_NUMBER = 3;
    private java.lang.Object password_;
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          password_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      aid_ = 0;
      passport_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, aid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPassportBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, aid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPassportBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.nettyserver.pb.MessageLoginProto.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.nettyserver.pb.MessageLoginProto.LoginRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.nettyserver.pb.MessageLoginProto.LoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nettyserver.pb.MessageLoginProto.internal_static_pb_message_LoginRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nettyserver.pb.MessageLoginProto.internal_static_pb_message_LoginRequest_fieldAccessorTable;
      }
      
      // Construct using com.nettyserver.pb.MessageLoginProto.LoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        aid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        passport_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nettyserver.pb.MessageLoginProto.LoginRequest.getDescriptor();
      }
      
      public com.nettyserver.pb.MessageLoginProto.LoginRequest getDefaultInstanceForType() {
        return com.nettyserver.pb.MessageLoginProto.LoginRequest.getDefaultInstance();
      }
      
      public com.nettyserver.pb.MessageLoginProto.LoginRequest build() {
        com.nettyserver.pb.MessageLoginProto.LoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.nettyserver.pb.MessageLoginProto.LoginRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.nettyserver.pb.MessageLoginProto.LoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.nettyserver.pb.MessageLoginProto.LoginRequest buildPartial() {
        com.nettyserver.pb.MessageLoginProto.LoginRequest result = new com.nettyserver.pb.MessageLoginProto.LoginRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.aid_ = aid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.passport_ = passport_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nettyserver.pb.MessageLoginProto.LoginRequest) {
          return mergeFrom((com.nettyserver.pb.MessageLoginProto.LoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.nettyserver.pb.MessageLoginProto.LoginRequest other) {
        if (other == com.nettyserver.pb.MessageLoginProto.LoginRequest.getDefaultInstance()) return this;
        if (other.hasAid()) {
          setAid(other.getAid());
        }
        if (other.hasPassport()) {
          setPassport(other.getPassport());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              aid_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              passport_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              password_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 aid = 1;
      private int aid_ ;
      public boolean hasAid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getAid() {
        return aid_;
      }
      public Builder setAid(int value) {
        bitField0_ |= 0x00000001;
        aid_ = value;
        onChanged();
        return this;
      }
      public Builder clearAid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        aid_ = 0;
        onChanged();
        return this;
      }
      
      // optional string passport = 2;
      private java.lang.Object passport_ = "";
      public boolean hasPassport() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPassport() {
        java.lang.Object ref = passport_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          passport_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassport(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        passport_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassport() {
        bitField0_ = (bitField0_ & ~0x00000002);
        passport_ = getDefaultInstance().getPassport();
        onChanged();
        return this;
      }
      void setPassport(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        passport_ = value;
        onChanged();
      }
      
      // optional string password = 3;
      private java.lang.Object password_ = "";
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassword(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000004);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      void setPassword(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        password_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:pb.message.LoginRequest)
    }
    
    static {
      defaultInstance = new LoginRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pb.message.LoginRequest)
  }
  
  public interface LoginResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 error = 1;
    boolean hasError();
    int getError();
    
    // optional bytes loginToken = 2;
    boolean hasLoginToken();
    com.google.protobuf.ByteString getLoginToken();
  }
  public static final class LoginResponse extends
      com.google.protobuf.GeneratedMessage
      implements LoginResponseOrBuilder {
    // Use LoginResponse.newBuilder() to construct.
    private LoginResponse(Builder builder) {
      super(builder);
    }
    private LoginResponse(boolean noInit) {}
    
    private static final LoginResponse defaultInstance;
    public static LoginResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nettyserver.pb.MessageLoginProto.internal_static_pb_message_LoginResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nettyserver.pb.MessageLoginProto.internal_static_pb_message_LoginResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private int error_;
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getError() {
      return error_;
    }
    
    // optional bytes loginToken = 2;
    public static final int LOGINTOKEN_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString loginToken_;
    public boolean hasLoginToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getLoginToken() {
      return loginToken_;
    }
    
    private void initFields() {
      error_ = 0;
      loginToken_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasError()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, error_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, loginToken_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, error_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, loginToken_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.nettyserver.pb.MessageLoginProto.LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.nettyserver.pb.MessageLoginProto.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.nettyserver.pb.MessageLoginProto.LoginResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.nettyserver.pb.MessageLoginProto.LoginResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nettyserver.pb.MessageLoginProto.internal_static_pb_message_LoginResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nettyserver.pb.MessageLoginProto.internal_static_pb_message_LoginResponse_fieldAccessorTable;
      }
      
      // Construct using com.nettyserver.pb.MessageLoginProto.LoginResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        error_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        loginToken_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nettyserver.pb.MessageLoginProto.LoginResponse.getDescriptor();
      }
      
      public com.nettyserver.pb.MessageLoginProto.LoginResponse getDefaultInstanceForType() {
        return com.nettyserver.pb.MessageLoginProto.LoginResponse.getDefaultInstance();
      }
      
      public com.nettyserver.pb.MessageLoginProto.LoginResponse build() {
        com.nettyserver.pb.MessageLoginProto.LoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.nettyserver.pb.MessageLoginProto.LoginResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.nettyserver.pb.MessageLoginProto.LoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.nettyserver.pb.MessageLoginProto.LoginResponse buildPartial() {
        com.nettyserver.pb.MessageLoginProto.LoginResponse result = new com.nettyserver.pb.MessageLoginProto.LoginResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.loginToken_ = loginToken_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nettyserver.pb.MessageLoginProto.LoginResponse) {
          return mergeFrom((com.nettyserver.pb.MessageLoginProto.LoginResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.nettyserver.pb.MessageLoginProto.LoginResponse other) {
        if (other == com.nettyserver.pb.MessageLoginProto.LoginResponse.getDefaultInstance()) return this;
        if (other.hasError()) {
          setError(other.getError());
        }
        if (other.hasLoginToken()) {
          setLoginToken(other.getLoginToken());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasError()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              error_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              loginToken_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 error = 1;
      private int error_ ;
      public boolean hasError() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getError() {
        return error_;
      }
      public Builder setError(int value) {
        bitField0_ |= 0x00000001;
        error_ = value;
        onChanged();
        return this;
      }
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = 0;
        onChanged();
        return this;
      }
      
      // optional bytes loginToken = 2;
      private com.google.protobuf.ByteString loginToken_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasLoginToken() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getLoginToken() {
        return loginToken_;
      }
      public Builder setLoginToken(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        loginToken_ = value;
        onChanged();
        return this;
      }
      public Builder clearLoginToken() {
        bitField0_ = (bitField0_ & ~0x00000002);
        loginToken_ = getDefaultInstance().getLoginToken();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:pb.message.LoginResponse)
    }
    
    static {
      defaultInstance = new LoginResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:pb.message.LoginResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_message_LoginRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_message_LoginRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_message_LoginResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_message_LoginResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027MessageLoginProto.proto\022\npb.message\"?\n" +
      "\014LoginRequest\022\013\n\003aid\030\001 \001(\005\022\020\n\010passport\030\002" +
      " \001(\t\022\020\n\010password\030\003 \001(\t\"2\n\rLoginResponse\022" +
      "\r\n\005error\030\001 \002(\005\022\022\n\nloginToken\030\002 \001(\014B\026\n\022co" +
      "m.nettyserver.pbH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pb_message_LoginRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pb_message_LoginRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pb_message_LoginRequest_descriptor,
              new java.lang.String[] { "Aid", "Passport", "Password", },
              com.nettyserver.pb.MessageLoginProto.LoginRequest.class,
              com.nettyserver.pb.MessageLoginProto.LoginRequest.Builder.class);
          internal_static_pb_message_LoginResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_pb_message_LoginResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pb_message_LoginResponse_descriptor,
              new java.lang.String[] { "Error", "LoginToken", },
              com.nettyserver.pb.MessageLoginProto.LoginResponse.class,
              com.nettyserver.pb.MessageLoginProto.LoginResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
