package com.nettyserver.network;

public enum ServerErrorID {
    SERVER_ERROR_OK,
    SERVER_ERROR_PASSPORT_INVALID,
    SERVER_ERROR_PASSWORD_INVALID,
    SERVER_ERROR_LOGIN_TOKEN_INVALID,
    SERVER_ERROR_MAX
}
